# Generated by Django 4.1.7 on 2023-03-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_step_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step_number',
        ),
    ]
