# Generated by Django 4.1.7 on 2023-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_rate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_recipes/')),
            ],
        ),
        migrations.CreateModel(
            name='StepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_recipe_steps/')),
            ],
        ),
        migrations.CreateModel(
            name='StepVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos_recipe_steps/')),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='step',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='step',
            name='recipe_photo',
        ),
        migrations.RemoveField(
            model_name='step',
            name='recipe_video',
        ),
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(related_name='recipes', to='recipes.recipeimage'),
        ),
        migrations.AddField(
            model_name='step',
            name='images',
            field=models.ManyToManyField(related_name='steps', to='recipes.stepimage'),
        ),
        migrations.AddField(
            model_name='step',
            name='videos',
            field=models.ManyToManyField(related_name='steps', to='recipes.stepvideo'),
        ),
    ]
