# Generated by Django 4.1.7 on 2023-03-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipeimage_stepimage_stepvideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_recipe_comments/')),
            ],
        ),
        migrations.CreateModel(
            name='CommentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos_recipe_comments/')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='images',
            field=models.ManyToManyField(related_name='comments', to='recipes.commentimage'),
        ),
        migrations.AddField(
            model_name='comment',
            name='videos',
            field=models.ManyToManyField(related_name='comments', to='recipes.commentvideo'),
        ),
    ]
