# Generated by Django 4.1.7 on 2023-03-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_commentimage_commentvideo_comment_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='cook_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='prep_time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
