# Generated by Django 4.1.7 on 2023-03-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_step_cook_time_step_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='base_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe'),
        ),
    ]
