# Generated by Django 4.1.7 on 2023-04-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_base_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to='videos_recipes/')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='videos',
            field=models.ManyToManyField(related_name='recipes', to='recipes.recipevideo'),
        ),
    ]
