# Generated by Django 4.1.7 on 2023-04-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipevideo_recipe_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipevideo',
            name='video',
            field=models.FileField(upload_to='videos_recipes/'),
        ),
    ]
