# Generated by Django 4.1.7 on 2023-03-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingitem',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shoppingitem'),
        ),
    ]
